src/toolbox/setup/fontbm.ts

Add fontbm setup #14 support for Linux.

linux support for fontbm

---

.github/workflows/build.yml
src/commands/setup.ts

chore: add build workflow action

---

src/commands/teardown.ts
src/toolbox/setup/pico.ts

Fixes #25 
Fixes #26 
This also adds the `fontbm` install directory to the set of `teardown` actions.

feat: teardown pico install, update to PICO_SDK_DIR

---

src/commands/run.ts

fix(run): fail early if example project does not exist

---

src/cli.ts

To help inform folks using xs-dev about new updates, this PR includes the [`checkForUpdates`](https://infinitered.github.io/gluegun/#/runtime?id=checkforupdates) configuration from Gluegun. (I thought I was going to have to do all that work manually 😅 )

fix(package): check for CLI updates occasionally

---

src/commands/include.ts
src/commands/remove.ts

This PR tries to address all of the include/remove notes except for editing the includes in the platform section (that looks possible but will take some more time).

address most include/remove notes in #32

---

README.md
src/commands/init.ts

feat(init): select template from moddable examples

---

README.md
src/commands/include.ts
src/commands/remove.ts

I tried to follow the style of the `init` command for handling the `--device` flag. I hope it is close.

--device for include and remove

---

package.json
pnpm-lock.yaml
src/toolbox/setup/constants.ts
src/toolbox/setup/esp32.ts
src/toolbox/setup/esp32/windows.ts
src/toolbox/setup/esp8266.ts
src/toolbox/setup/esp8266/windows.ts
src/toolbox/setup/windows.ts

This commit merges together everything from PR #53. Initial Windows support for xs-dev, including Moddable SDK tools, ESP32 support, and ESP8266 support.

feat: add Windows support for xs-dev/tools, ESP32, and ESP8266

---

.changeset/lovely-papayas-admire.md
src/commands/teardown.ts

fix(teardown): remove xsbug symlink on macos

---

.changeset/cyan-camels-boil.md
src/commands/teardown.ts

fix(teardown): use correct reference for Darwin

---

src/extensions/setup-extension.ts
src/extensions/update-extension.ts
src/toolbox/build/index.ts
src/toolbox/prompt/devices.ts
src/toolbox/setup/esp32.ts
src/toolbox/setup/esp8266.ts
src/toolbox/setup/esp8266/mac.ts
src/toolbox/setup/esp8266/windows.ts
src/toolbox/setup/moddable.ts
src/toolbox/setup/pico.ts
src/toolbox/setup/wasm.ts
src/types.ts

Fixes #78 
Fixes #79 
Fixes #72

fix: add env checks before attempting to run project code

---

src/toolbox/setup/pico.ts

fix(pico): pin branch for sdk, examples

---

src/toolbox/setup/pico.ts

Pico I2S support is in extras. Needed for audio playback.

install pico extras

---

package.json
pnpm-lock.yaml

Updating the [astro](https://astro.build) and [starlight](https://starlight.astro.build) dependencies to get the latest and greatest from those documentation generation tools.

chore: update astro + starlight deps

---

src/toolbox/setup/esp8266.ts

ESP8266 for Windows setup was broken by 0c8d555 (see [Moddable SDK #1196](https://github.com/Moddable-OpenSource/moddable/issues/1196#issuecomment-1688944632)). This commit restores the correct ZIP file path for Windows and the ZIP-specific toolchain unzip functionality.

fix(setup): fix ESP8266 setup on Windows

---

docs/src/content/docs/troubleshooting.md
src/toolbox/setup/nrf52.ts

fix(setup/nrf52): create the decompression stream when needed

---

src/toolbox/setup/esp32.ts
src/toolbox/update/esp32.ts

Fixes #155 
I added some additional logic to prompt updating the Moddable SDK before fetching the new ESP-IDF release.

feat(esp32): update esp-idf version to support latest Moddable SDK

---

docs/src/content/docs/features/run.md
docs/src/content/docs/features/scan.md
docs/src/content/docs/features/update.md
docs/src/content/docs/guide/00-prepare.md
docs/src/content/docs/guide/01-hello-console.md

docs: update broken links

---

src/toolbox/setup/esp32.ts
src/toolbox/update/esp32.ts

This PR includes some update for #164.

 feat(update): use v5.2.2 tag of esp-idf (#164)

---

package.json
pnpm-lock.yaml

Keeping up to date with the latest releases of Astro and Starlight to keep the docs in good shape.

chore(docs): upgrade astro, starlight deps

---

src/toolbox/setup/esp32.ts
src/toolbox/update/esp32.ts

feat(esp32): update esp-idf version to 5.4.0
