HipsterBrown/xs-dev

- src/toolbox/setup/esp32.ts
- src/toolbox/update/esp32.ts
- src/toolbox/update/mac.ts
With the update to v4.4 of the esp-idf tooling in Moddable (https://twitter.com/moddabletech/status/1493734039991164932), this PR adds support for that tagged version for the `setup` and `update` commands for the ESP32.
> feat(update): add esp32 support, use v4.4 branch of esp-idf

- README.md
- package.json
- pnpm-lock.yaml
- src/commands/scan.ts
- src/toolbox/scan/parse.ts
Fixes #12 
This feature uses [SerialPort](https://serialport.io/) to list all ports and call `esptool.py` for each relevant port since `esptool.py` stops at the first available device, which is an issue if you have multiple devices connected for testing.
> feat: add scan command

- src/commands/run.ts
- src/commands/setup.ts
- src/toolbox/prompt/devices.ts
Fixes #29 
Also resolves displaying the correct device alias for the current OS platform in the `setup` command's list of devices.
> feat: include pico in run and setup device list, add simulators list

- src/commands/scan.ts
This fixes the problem of `esptool.py`failing on one device getting in the way of scanning other devices. It doesn't try to add support for scanning Pico.
> scan continues on failure #27

- src/toolbox/setup/pico.ts
When attempting to run the hello world example for the pico on my M1 Mac, I ran into an error related to the directory for `arm-none-eabi-gcc`. The default directory within the [Moddable make file](https://github.com/Moddable-OpenSource/moddable/blob/public/tools/mcconfig/make.pico.mk#L26) is `/usr/local`, which is the default for Homebrew on Mac machines running on Intel chips. 
This PR fixes the error by setting the `PICO_GCC_ROOT` environment variable to the `brew --prefix` result on MacOS. Instead of doing it conditional to the architecture of the machine, `PICO_GCC_ROOT` will always be set for safety.
> fix(pico): set PICO_GCC_ROOT to brew prefix on mac

- README.md
- src/commands/scan.ts
- src/toolbox/scan/parse.ts
- src/toolbox/setup/esp32.ts
- src/toolbox/setup/pico.ts
- src/toolbox/setup/pico/linux.ts
- src/toolbox/setup/pico/mac.ts
The [picotool CLI](https://github.com/raspberrypi/picotool) is a handy utility for inspecting and interacting with devices using the pico chipset (RP2040). This is potentially useful for xs-dev users as a means of including pico info in the `scan` command output. The `picotool` CLI itself doesn't not include a `list` feature but the `info` command may provide a similar output. 
Sample output:
```text
❯ picotool info -fa
The device was asked to reboot into BOOTSEL mode so the command can be executed.
Program Information
name:          helloworld
web site:      https://github.com/Moddable-OpenSource
features:      USB stdin / stdout
binary start:  0x10000000
binary end:    0x1003a120
Fixed Pin Information
none
Build Information
sdk version:       1.1.0
pico_board:        pico
boot2_name: …
```
> feat(pico): include picotool CLI in setup command

- src/commands/scan.ts
Fixes #45 
Uses the suggested command `picotool reboot -fa` to set any connected pico board in boot select into application mode for serial discovery, and it does require a second to reboot before appearing as an available device. 
The data returned by `Serialport.list` does not include USB bus information, so running `picotool` against a particular USB address is not possible unless I am able to refactor to use [node-usb](https://node-usb.github.io/node-usb/) instead. Node-usb might actually be the more appropriate library for the use case of `xs-dev`, so it is worth attempting the refactor in a separate branch.
> fix(scan): reboot pico boards in BOOTSEL before scan

- package.json
- pnpm-lock.yaml
- src/commands/scan.ts
Follow up from #46 to spike on using [node-usb](https://node-usb.github.io/node-usb/) to get the USB bus number and address to pass to the `picotool info` command.
> fix(scan): filter picotool info by bus + address

- docs/src/components/Header/Header.astro
- docs/src/components/Header/Search.css
- docs/src/components/Header/Search.tsx
- docs/src/pages/search-index.json.ts
- package.json
- pnpm-lock.yaml
To help with discovery of xs-dev information, this PR adds a Search component that uses [fuse.js](https://fusejs.io/) and a custom JSON endpoint to store the searchable content.
Preview:
> docs: add Search component w/ fuse.js

- src/toolbox/setup/esp32.ts
- src/toolbox/update/esp32.ts
The Moddable SDK will be updating to use ESP-IDF v4.4.2 shortly. I'm getting the same move staged here while I'm updating files in the Moddable SDK.
I'll flip this out of draft when the Moddable SDK change goes live to GitHub.
> feat(update): use v4.4.2 tag of esp-idf

- bin/xs-dev
- docs/src/pages/en/features/setup.md
- docs/tsconfig.json
- package.json
- pnpm-lock.yaml
- src/commands/setup.ts
- src/toolbox/setup/linux.ts
- src/toolbox/setup/mac.ts
- src/toolbox/setup/moddable.ts
- src/toolbox/setup/types.ts
- src/toolbox/setup/windows.ts
- src/types.ts
Fixes #24 
Tested on Mac and Linux. This PR avoids building the Moddable tooling during the setup process, using the prebuilt release assets from GitHub and doing a shallow clone of the tagged branch instead. On linux, it is still required to to a bit of the build process to get the desktop applications installed correctly. 
Docs:
> feat(setup): add target-branch option, pull latest release by default

- docs/src/pages/en/features/update.md
- src/commands/update.ts
- src/toolbox/setup/moddable.ts
- src/toolbox/update/linux.ts
- src/toolbox/update/mac.ts
- src/types.ts
Follow up to #57 for the `update` command. There is probably some room for refactoring the common functionality around using the latest release assets but that can be explored later as the Windows platform support comes online.
> feat(update): add target-branch option, pull latest release by default

- .changeset/slimy-crabs-rush.md
- .gitignore
- docs/src/pages/en/features/run.md
- src/commands/build.ts
- src/commands/run.ts
- src/extensions/build-extension.ts
- src/toolbox/build/index.ts
- src/types.ts
This PR includes a refactor of the build and run logic for Moddable projects in the `run` command for reuse in a separate `build` command to help with preparing for a production environment release. 
Updated docs page:
> feat(build): add initial command w/ deploy flag

- docs/src/pages/en/features/init.md
- src/commands/init.ts
- src/templates/manifest.json.ejs
Addresses #65
I'm not proud of the approach I took to keep the JSON "pretty". I didn't want an empty defines object being output when asyncMain was not invoked, but if another defines option is added, this will become awkward.
Creating a JSON object and writing the stringified object to the filesystem might be more future proof than using strings and an ejs template.
Finally, the property name for XS' manifest.json is `async_main`, but ES Lint complains about that style so I've used `asyncMain` for the param. It bothers me that they don't match, but a contributor changing `.eslint.js` is kinda like having a houseguest rearrange furniture. I don't want to be that guy.
> Adds asyncMain option to init command

- src/toolbox/setup/windows.ts
If a user runs `xs-dev setup` from a standard command prompt (rather than the VS Code or Moddable command prompts), `xs-dev` would attempt to automatically install VS Code 2022 even if it was already installed. This fix instead prompts the user before installing so that they can back out and run the correct command prompt if needed. (It is generally difficult to determine if VS Code has been installed on a system if the user did not run the VS Code command prompt, unfortunately.)
> feat(setup): prompt before attempting to install VS 2022 Community

- src/toolbox/setup/esp32.ts
- src/toolbox/setup/esp32/mac.ts
- src/toolbox/setup/esp8266.ts
- src/toolbox/setup/esp8266/mac.ts
- src/toolbox/setup/fontbm.ts
- src/toolbox/setup/homebrew.ts
- src/toolbox/setup/pico.ts
- src/toolbox/setup/pico/mac.ts
- src/toolbox/setup/wasm.ts
Fixes #77 
----
The currently error handling for ensuring Homebrew is available suggests users to visit https://brew.sh/ and follow the instructions there. This is another prompt that can handle this task automatically if the user chooses.
> fix: ensure homebrew is available before running install commands

- package.json
- pnpm-lock.yaml
- src/toolbox/setup/esp8266.ts
- src/toolbox/setup/esp8266/windows.ts
Fixes #76 
Confirmed this works on Linux and Mac. I also updated the `axios` dependency to the stable v1+ and pinned the version of node used in this project to 18.12.1 (current LTS). The CLI will continue to support maintenance & LTS versions of NodeJS until they are removed from [support by the core project](https://github.com/nodejs/release#release-schedule).
> fix: update source for esp8266 toolchain

- .changeset/stale-cars-sniff.md
- src/toolbox/setup/mac.ts
- src/toolbox/setup/moddable.ts
- src/toolbox/update/mac.ts
As informed by @mkellner, the latest Moddable release includes a universal prebuilt binary for MacOS alongside the arch-specific builds. This PR adds logic to the setup and update commands to try using that universal binary if available before falling back to the arch-specific targets.
> feat(mac): try mac universal binaries in setup/update

- docs/src/pages/en/features/run.md
- src/commands/build.ts
- src/commands/run.ts
- src/toolbox/build/index.ts
This PR addresses issue #101. 
It implements the last suggestion by @phoddie, allowing `--config.ssid=MyWiFi` and `--config.password="a secret"`.
The change to add `shell: true` to the call to `system.exec` was necessary to preserve quotes around configuration items on Windows without weird escaping issues.
I welcome suggestions from TypeScript experts on how to better accomplish this while still keeping the linter happy 😆: 
```typescript
configArgs.push(`${element}="${config[element as keyof typeof config] as string}"`)`
```
> Add optional configuration arguments to build and run commands

- .github/workflows/build.yml
- .github/workflows/docs-deploy.yml
- .github/workflows/release.yml
- .gitignore
- package.json
- pnpm-lock.yaml
To support smooth merge -> release workflows, this PR introduces [release-it](https://github.com/release-it/release-it) to generate new package releases based on [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/). Any push to `main` should trigger this workflow. The workflows have also been updated to take advantage of caching node modules between builds.
> chore: add automated releases

- docs/src/pages/en/features/setup.md
- src/commands/build.ts
- src/commands/doctor.ts
- src/commands/include.ts
- src/commands/init.ts
- src/commands/run.ts
- src/commands/scan.ts
- src/toolbox/build/index.ts
- src/toolbox/setup/esp32.ts
- src/toolbox/setup/esp8266.ts
- src/toolbox/setup/pico.ts
- src/toolbox/setup/wasm.ts
- src/toolbox/system/exec.ts
- src/toolbox/update/esp32.ts
- src/toolbox/update/linux.ts
- src/toolbox/update/mac.ts
Fixes #110 🤞 
Following the suggestion from @phoddie, this PR adds an additional step to various commands to update the `process.env` object with information from the user shell after manually "sourcing" the `xs-dev-exports` file on Unix-like systems. This appears to allow running examples immediately after setup without creating a new shell session. 
This PR also adds a "Shell" field to the output of `xs-dev info` to help with debugging; as well as, an "Environment config" section of the `setup` docs page to provide more info about the use of the "exports" file.
> feat: automatically source environment variables into process

- docs/src/pages/en/guide/01-hello-console.md
- docs/src/pages/en/introduction.md
- src/toolbox/system/exec.ts
I did some debugging for the "environment sourcing" fix from #112 and found a case where the `spawn` process returns a Buffer instead of a string. With this case handled, this should work better for folks.
This PR also includes some documentation updates:
Introduction video on the homepage
Troubleshooting section in the "Hello Console" guide
> fix(exec): check for buffer response from stdout, convert to string

- docs/src/pages/en/features/setup.md
- src/commands/setup.ts
- src/toolbox/setup/linux.ts
- src/toolbox/setup/mac.ts
- src/toolbox/setup/types.ts
- src/toolbox/setup/windows.ts
- src/types.ts
From the updated `setup` docs:
> ## Target Branch
>
>The default behavior of this command for Moddable developer tooling pulls the [latest release tooling](https://github.com/Moddable-OpenSource/moddable/releases) and source code for the associated tagged branch. This provides a known-working state for the SDK and avoids needing to build the tooling on the local machine. 
>
>To override this behavior, use the `--target-branch` flag to select `public`; this fetches the latest commit off that main branch and runs the build to generate the associated tools. This can be set to any branch name, however `public` is the main public branch for the Moddable-OpenSource repo.
>
>```
>xs-dev setup --target-branch public
>```
>
>When combined with the `--source-repo` flag, it's possible to get the SDK …
> feat(setup): add --source-repo flag for custom SDK repo config

- docs/astro.config.mjs
- docs/src/content/docs/troubleshooting.md
- package.json
- pnpm-lock.yaml
- src/toolbox/setup/nrf52.ts
For development environments that don't have xz utils available for the node-lzma native bindings, that dependency is now optional until attempting to setup the nrf52 tooling on Linux or MacOS. If node-lzma is not available, a helpful error message will be displayed.
I've also added a new "Troubleshooting" page that can be indexed to help folks find solutions to known issues. 
---
In the future, it could be helpful to prompt xs-dev users to automatically install the XZ utils and attempt to install node-lzma after; rather than just display an error. I'm not sure how to do this without more experimentation, so this patch will suffice for the time being.
> fix(nrf52): make node-lzma an optional dep, handle dynamic import

- src/toolbox/setup/moddable.ts
When working with a custom branch of the Moddable SDK, the `xs-dev doctor` / `xs-dev info` command doesn't always detect git tags for determining the version of the SDK being used. This patch ensures the fallback `branch` and `commit` detection works for the SDK version as well. 
In newer releases of the SDK, the debug tools are not always available or built by default. So this patch also removes the strict detection of that tools directory for determining if the SDK has been set up correctly.
> fix: remove dep on debug tools dir, ignore empty git tag

- src/toolbox/build/index.ts
- src/toolbox/setup/esp32.ts
- src/toolbox/setup/moddable.ts
- src/toolbox/update/esp32.ts
Following the release of [Moddable 4.2](https://github.com/Moddable-OpenSource/moddable/releases/tag/4.2.0), this PR adds support for updating to v5 of the ESP-IDF if the latest Moddable SDK is setup on the developer's system. 
Using `xs-dev update && xs-dev update --device esp32` will allow developers to get the latest and greatest without breaking a sweat. 
The release includes the new `mcpack` CLI to provide integration with third-party JS modules discovered through a `package.json` file, so xs-dev provides automatic usage of that utility when a `package.json` file is located within the current working directory during the `build` or `run` commands. As feedback comes in from the community, I hope to provide deeper support for third-party modules like scaffolding a publishable module …
> feat: add support for ESP-IDF v5 & mcpack

- src/toolbox/setup/esp32/linux.ts
Changed the package name from python-setuptools to python3-setuptools
Fixes #151
> fix(setup/esp32): update a package name in linux.ts

- src/toolbox/setup/pico/mac.ts
- src/toolbox/update/pico.ts
Fixes #153 
Also added support for the `update` command for the pico tooling. This will be useful for using the new dependency on macOS without tearing down and setting up the pico tooling again, as well as any future updates like the pinned git branch.
> feat(pico): add update command, use new gcc-arm-embedded cask on mac

- src/toolbox/setup/esp32.ts
- src/toolbox/update/esp32.ts
[Moddable SDK 4.9.5](https://github.com/Moddable-OpenSource/moddable/releases/tag/4.9.5) recommends using [ESP-IDF v5.3](https://github.com/espressif/esp-idf/releases). This PR update branch `ESP_BRANCH_V5`.
> feat(update): use v5.3 tag of esp-idf

- docs/src/content/docs/features/run.md
- src/commands/clean.ts
- src/commands/debug.ts
- src/toolbox/build/index.ts
Fixes #121 
To properly support the range of build target options accepted by `mcconfig`, this PR introduces the `clean` and `debug` commands. 
Docs Preview:
> feat: add clean and debug commands

- docs/src/content/docs/features/setup.md
- src/toolbox/setup/esp32.ts
- src/toolbox/setup/linux.ts
- src/toolbox/setup/mac.ts
Fixes #161 
Also, removes sourcing `$IDF_PATH/export.sh` automatically since the Moddable SDK takes care of it.
> fix(setup): remove xs-dev-export.sh sourcing from shell profile

- src/commands/scan.ts
- src/toolbox/system/exec.ts
Fixes #98 
Also addresses introduced by #170 with the removal of `source $IDF_PATH/exports.sh` from the `xs-dev-exports.sh`.
> fix(scan): source esp_idf before checking for esptool.py

- src/toolbox/build/index.ts
- src/toolbox/system/exec.ts
After updating the environment sourcing for ESP_IDF in #170, there were errors when attempting to build or run projects targeting the ESP32 related to the default Python environment not including all the requirements for the `idf.py` operations. 
This PR sources the Python virtual environment created by the ESP_IDF on demand, which resolves the issue.
> fix(esp32): source IDF python env when building, running project

- src/toolbox/build/index.ts
- src/toolbox/prompt/choices.ts
Fixes #175
This also adds a check for NRF52 platform target support, similar to the checks for esp8266, esp32, pico, and wasm.
> fix(build/run): dynamically create list of device targets

- .all-contributorsrc
- .github/workflows/release.yml
- .gitignore
- README.md
- package.json
- pnpm-lock.yaml
The default behavior of [release-it](https://github.com/release-it/release-it) is a patch release, regardless of the commit type, which goes against the expected [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) behavior. 
To reduce the amount of noisy releases and support new workflows (like canary releases from PRs and documenting contributors), this pull request introduces [auto](https://intuit.github.io/auto/index) in place of release-it.
> chore: replace release-it with auto

- src/commands/setup.ts
- src/commands/update.ts
- src/toolbox/prompt/devices.ts
- src/toolbox/setup/pico.ts
- src/toolbox/update/pico.ts
The Moddable SDK now depends on version 2.0.0 of the Raspberry Pi Pico SDK: https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/devices/pico.md#sdk-and-host-environment-setup
This PR updates the version used by the `setup` and `update` commands. 
<details>
<summary>📦 Published PR as canary version: <code>0.32.8--canary.181.e4479a4.0</code></summary>
<br />
:sparkles: Test out this PR locally via:
```bash
npm install xs-dev@0.32.8--canary.181.e4479a4.0
yarn add xs-dev@0.32.8--canary.181.e4479a4.0
```
</details>
> feat(pico): update SDK to v2.0.0

- docs/src/content/docs/guide/usage-with-typescript.mdx
Added my version of the TypeScript starter template as a first step for https://github.com/HipsterBrown/xs-dev/issues/186
> Add TypeScript usage example

- src/commands/init.ts
- src/toolbox/init/templates.ts
- src/toolbox/setup/pico.ts
While working on a project with the Raspberry Pi Pico (RP2040), I was unable to run any programs targeting the device after `xs-dev setup --device pico`. 
Part of this was due to the `picotool` CLI not building because xs-dev was cloning the `master` branch instead of the matching pico-sdk version (2.0.0 vs 2.1.0 which just released recently). 
Once that was resolved, the `pioasm` binary was unexpectedly missing but required by the Moddable SDK for the `pico` device target. As part of the major update from v1.5.1 to v2.0.0, the pico-sdk build stopped including `pioasm` by default, relying on developers to include that tool's CMake bootstrapping instructions in their CMakeLists.txt as needed. This was fixed in xs-dev by adding the cmake/make commands for pioasm after the default build for …
> fix(setup/pico): pin picotool repo branch, add pioasm build step

- src/toolbox/setup/pico.ts
To run a program targeting the pico with `mcpack` or `mcconfig` (depending on the included SDK modules), the PICO_EXAMPLES_DIR and PICO_EXTRAS_DIR environment variables need to be set (see https://github.com/Moddable-OpenSource/moddable/blob/public/build/devices/pico/manifest.json#L2-L5). The default expected paths don't match the conventions set by xs-dev, so they should be able to override in the `moddable.manifest` config in the package.json or in the `manifest.json` file. Until then the default manifest.json for the pico needs to be manually edited to remove the `build` variables settings. 
I will follow up in the Moddable SDK repo to resolve this going forward.
> fix(setup/pico): set PICO_EXAMPLES_DIR env var in exports file

- src/commands/build.ts
- src/commands/clean.ts
- src/commands/debug.ts
- src/commands/init.ts
- src/commands/run.ts
- src/commands/setup.ts
- src/commands/update.ts
Discovered a few regressions from the refactor to use Strcli while building a few projects with xs-dev recently:
- the multi-word command flags, such as `--list-examples` or `target-branch`, were accidentally changed to camelCase from the original kebab-case
- the `--device` flag for the `build` / `run` / `clean` / `debug` commands was made an enum to match the `setup` command, however it should accept the "sub-target" device specifiers, i.e. `esp32/s3`, as well
Both of these are resolved in this PR. I opted for making the `--device` flag just a string argument instead of expanding the enum of values to reduce complexity of trying to fetch all the available options before building the command object and exploding the generated help text. 
<details>
<summary>📦 Published PR as canary …
> fix: use kebab-case command flags, loosen device target typing for build/run commands

- docs/src/content/docs/features/setup.md
- docs/src/content/docs/features/update.md
- src/commands/init.ts
- src/commands/setup.ts
- src/commands/update.ts
- src/toolbox/prompt/choices.ts
- src/toolbox/setup/linux.ts
- src/toolbox/setup/mac.ts
- src/toolbox/setup/moddable.ts
- src/toolbox/setup/types.ts
- src/toolbox/setup/windows.ts
- src/toolbox/update/linux.ts
- src/toolbox/update/mac.ts
When attempting to update to the [latest Moddable SDK release](https://github.com/Moddable-OpenSource/moddable/releases/tag/5.3.3), I ran into missing release assets after pulling the tagged branch and resulting in a broken setup. To fix this and make the `setup` and `update` commands more flexible for versioned release installs, I updated those commands to split the `--target-branch` flag into `--release` and `--branch`: the former providing tagged release support and the latter providing support for any remote branch name.
> feat(setup/update): split target-branch into release, branch options

- src/toolbox/setup/esp32.ts
- src/toolbox/update/esp32.ts
To support [v5.3.0+ of the Moddable SDK](https://github.com/Moddable-OpenSource/moddable/releases/tag/5.3.0), this PR updates the version of the ESP-IDF to v5.3.1.
> feat(esp32): update esp-idf version to 5.3.1

- src/commands/scan.ts
- src/toolbox/setup/linux.ts
- src/toolbox/setup/mac.ts
- src/toolbox/setup/windows.ts
- src/toolbox/update/linux.ts
- src/toolbox/update/mac.ts
- src/toolbox/update/pico.ts
After adding support for installing & updating the Moddable SDK from a specific tagged release version in #197, I was still running into the need for building the tooling (mcconfig, mcpack, simulator, etc) when not included in the release assets. This PR adds support for that workflow after confirming with the user. 
Also included is a fix for updating the pico support by removing the unnecessary `git clone` of the `pico-extras` repo before fetching tags and pulling the required SDK branch.
> fix(setup,update):  build SDK tools if not included in tagged release

- src/toolbox/setup/linux.ts
- src/toolbox/setup/mac.ts
- src/toolbox/setup/windows.ts
Moddable SDK 5.3.3 is released without pre-built binaries. "xs-dev setup" requires the prompt, but it doesn't work in spinner working.  https://github.com/HipsterBrown/xs-dev/pull/200
Reproduced on mac and linux.
This change fixes the prompt issue.
https://github.com/HipsterBrown/xs-dev/issues/201
> fixed: stop spinner before prompt

- docs/src/content/docs/features/setup.md
- docs/src/content/docs/features/update.md
- src/commands/setup.ts
- src/commands/update.ts
- src/toolbox/setup/linux.ts
- src/toolbox/setup/mac.ts
- src/toolbox/setup/moddable.ts
- src/toolbox/setup/types.ts
- src/toolbox/setup/windows.ts
- src/toolbox/update/linux.ts
- src/toolbox/update/mac.ts
Fixes #204 
Preview of new help text:
```console
USAGE
xs-dev setup [--device esp|esp8266|darwin|mac|windows_nt|windows|win|linux|lin|esp32|wasm|pico|nrf52] [--list-devices] [--tool ejectfix] [--branch value] [--release value] [--source-repo value] [--interactive]
xs-dev setup --help
Download and build Moddable tooling for various platform targets
FLAGS
[--device]                         Target device or platform SDK to set up; defaults to Moddable SDK for current OS; use --list-devices for interactive selection [esp|esp8266|darwin|mac|windows_nt|windows|win|linux|lin|esp32|wasm|pico|nrf52]
[--list-devices/--noList-devices]  Select target device or platform SDK to set up from a list; defaults to false
[--tool]                           Install additional tooling to support common …
```
> feat(setup/update): add interactive mode

- README.md
- docs/src/content/docs/features/doctor.md
- docs/src/content/docs/guide/00-prepare.md
- docs/src/content/docs/guide/01-hello-console.md
Fixes #202
This project is committed to supporting at least the [active LTS version of NodeJS](https://nodejs.org/en/about/previous-releases#nodejs-releases). This is now documented in the README and getting started guide.
> docs: update NodeJS version requirements

- src/toolbox/setup/esp32.ts
- src/toolbox/update/esp32.ts
It can be used from [Moddable 5.10.1](https://github.com/Moddable-OpenSource/moddable/releases/tag/5.10.1) onwards.
> Track the dependent version of ESP-IDF 

- src/toolbox/system/packages.ts
Fix #216 
Updated installPackages to use `sudo` instead of `pkexec` when running in CI environments. This ensures compatibility with CI systems where pkexec may not be available or suitable.
> Use sudo for package install in CI environments
